### ISSUE TITLE
Define scope

### ISSUE THREAD

**Issue by rgaudin** [openzim/freecodecamp#7]
The README should clearly state a couple of points that are currently missing:

- Where to find the list of courses (and how to format)
- What the _scope_ of this scraper is: what it does in comparison to live FCC
- What are its current limitations

**Comment by mdp** [comment]
Currently the Javascript Challenges are the only ones that can ask a user to write code that's then tested. The other challenges usually contain a video the user needs to watch, and then a multiple choice test. 

For the first pass we wanted to support Javascript. In order to support more content we'll need to address #8 and #9

For now I'll update the readme with the supported course and the format of the list.
